### ISSUE TITLE
toggle zone

### ISSUE THREAD

**Issue by n3roGit** [mwittig/pimatic-milight-reloaded#10]
There is an little issue when toggle a rgb zone.

if i turn off "milight-rgbw-zone-1" over pimatic and after this i try a roule to toggle it, goes only to 1%.

**Comment by mwittig** [comment]
Haven't seen that, yet. Will try to reproduce the problem

**Comment by mwittig** [comment]
Do you have the new iBox controller or an old one?

**Comment by mwittig** [comment]
Should be fixed now, as off pimatic-milight-reloaded@0.9.9
Please reopen if you're still having issues

**Comment by n3roGit** [comment]
It's working :) thx!
