### ISSUE TITLE
Rule "if turned off" 

### ISSUE THREAD

**Issue by n3roGit** [mwittig/pimatic-milight-reloaded#12]
Hi, 

I don't know why but my rules with "if milight-rgbw-zone-3 is off than" doesn't work. 
But is works with my normal 433mhz Switches.

**Comment by mwittig** [comment]
For sure, this is caused by the fix for #10 
I need to find a better solution to cover both

**Comment by mwittig** [comment]
Should be fixed now with version 0.9.13.
